### ISSUE TITLE
i18n in gluon-config-mode-site-select is broken

### ISSUE THREAD

**Issue by rotanid** [freifunkMUC/gluon-packages#2]
the i18n which was introduced with ca27b7aeb6a9f835ff036382edda117318e0c7e3 doesn't work, the configuration interface shows the english text for the segment choice, although everything else is in german.

**Comment by krombel** [comment]
Since 2018.1 there is a [multidomain feature](https://gluon.readthedocs.io/en/v2018.1.x/features/multidomain.html) in gluon. This propably makes this package obsolete

**Comment by rotanid** [comment]
@krombel only if a migration package/script is written, that migrates the nodes from this package to the "official" Gluon solution

**Comment by krombel** [comment]
gluon-config-mode-site-select is not used anymore => closing it

The migration gets implemented by [gluon-domain-migration-ffmuc](https://github.com/freifunkMUC/gluon-packages/tree/master/gluon-domain-migration-ffmuc)
